#!/bin/bash
# Program:
# renew docker contaner
# History:
# 08/07/2016
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export=PATH

app_container='test_strider_node'
result=$( docker rm -f $app_container )
echo ${result}
if [ '${result}'=='${app_container}' ]; then
  docker run --name ${app_container} -v /my_apps/prjStrider/appNodeJSTest:/app -p 5010:5000 -d strider/nodejs_test 
fi
